services:
  frontend:
    image: frontend
    build: ./client
    container_name: frontend
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  backend:
    image: backend
    build: ./server
    container_name: backend
    restart: always
    ports:
      - "5000:5000"

volumes:
  dbdata: